# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b46595aabe023e43f6e76372a041f856b2454f3d63616dc7e77f81eee5b52f3bf6bd75c58a6693472ef5ae7865ab773b1320594f47b4e05feb740bbd970bdf43

test:
  secret_key_base: 76dce1c58860b0cefc3ac92bccc64a40202f7cbc81512ef1cb0f364274d4f01d9122fc0bc233b3738da701e98270ad36802beab6c405a7fe250eef65b52ac88d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
